### PR TITLE
Fix getBlocks return BlockState instead of Block

### PR DESCRIPTION
**Pull request by QuentiumYT**
Hello, I checked PortalCreateEvent and it seems to return a BlockState from getBlocks() method.
And then get the Block from this BlockState.

It fixes the issue on my end so why not making a pull request :)

### CODE REVIEW

**Comment by SpraxDev** [comment]
Thanks for your contribution!

Did it cause an error on your end?
And on what server version did you test the change?

**Comment by QuentiumYT** [comment]
Yes, when I tried to compile, I got an issue at this point. I'm using java 16
I tested it on a 1.17.1 server

**Comment by SpraxDev** [comment]
Yes, if you target more recent spigot version e.g. 1.17, you get an error. But as far as I know, this plugin works on 1.8 and 1.17

I think old versions need `Block` there as there has been an API change

**Comment by QuentiumYT** [comment]
Oh I see. I do have used java 8 right now and this PR is still working with the API. I do not have any error while compiling.

I haven't tested it yet on a server yet.

**Comment by SpraxDev** [comment]
I've enabled the workflow run and got the error I was expecting:
`
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project EpicAnchors: Compilation failure
Error:  /home/runner/work/EpicAnchors/EpicAnchors/src/main/java/com/songoda/epicanchors/listener/BlockListener.java:[71,40] incompatible types: org.bukkit.block.Block cannot be converted to org.bukkit.block.BlockState
`

Did you change the spigot version in your `pom.xml`?

**Comment by QuentiumYT** [comment]
Well apparently it doesn't compile here. I ran both java 8 and java 16 and I do not have any error.
I edited the pom.xml, but for the compilation purpose, I just reseted the git to the master branch.
This GH action is using java 16 as well so I have no clue about this class type error.

Anyway, I thought it would have been a fix but apparently, it works fine in here ^^
Thanks for your time :)
